config/routes.rb
Rails.application.routes.draw do
  get '/products', to: 'products#index'
  get '/products/new', to: 'products#new'
  post '/products', to: 'products#create'
  get '/product/:id', to: 'products#show', as: 'product'
  get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch '/product/:id', to: 'products#update'
  put '/product/:id', to: 'products#update'
  delete '/product/:id', to: 'products#delete'
  #resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
        
      end
    
      def new
        @product = Product.new
        variable_prueba=0
       

      end
    
      def create
        @product = Product.new(product_params)
          if @product.save
            redirect_to products_path
          else
            render :new
          end
      end
    
      def edit
        @product = Product.find(params[:id])
      end
    
      def update
        @product = Product.find(params[:id])
          if @product.update(product_params)
            redirect_to products_path
          else
            render :edit
          end
      end
    
      def delete
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
      end
    
      private
        def product_params
          params.require(:product).permit(:name, :description, :price)
        end
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<div class="alert alert-primary" role="alert">
<div class="jumbotron text-center alert-info" role="alert">
<h1>Editar Ciudad</h1>
</div>
</div>
<div class="container">
<div class="alert alert-primary" role="alert">
<%= form_for @product do |f| %>
  <div>
    
     <h6> Ingrese nombre </h6>
    <%= f.text_field :name %>
  </div>
  <br>

  <div>
    <h6> Descripcion </h6>
    <%= f.text_area :description %>
  </div>
  <div>
    <h6> Precio </h6>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<div class="alert alert-primary" role="alert">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


</div>

<div class="container text-center">
<%= link_to "Crear Producto", products_new_path %>
</div>

<div class="container">
<div class="alert alert-dark" role="alert">
<table border="2"  class="table table-hover table-striped">
    <tr>
         <th scope="col"></th>
         <th scope="col">Nombre</th>
        <th scope="col">Descripción</th>
        <th scope="col">Precios</th>
    </tr>
  
  
    <% @products.each do |product| %>
    <tr>
      <td> <%= link_to "Editar", edit_product_path(product) %> 
      <%= link_to "Eliminar", product, method: :delete, data: { confirm: "Deseas eliminar este artículo?"} %>
      <th><%= product.name %></th>
    <th><%= product.description %></th>
    <th><%= product.price %></th>
     
    </tr>
    
  
   <% end %>
  
    
</table>
  

app/views/products/new.html.erb
<div class="alert alert-primary" role="alert">
<div class="jumbotron text-center alert-info" role="alert">
<h1>Editar Ciudad</h1>
</div>
</div>

<div class="container">
<div class="alert alert-primary" role="alert">
<%= form_for @product do |f| %>
  <div>
    
     <h6> Ingrese nombre </h6>
    <%= f.text_field :name %>
  </div>
  <br>

  <div>
    <h6> Descripcion </h6>
    <%= f.text_area :description %>
  </div>
  <div>
    <h6> Precio </h6>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>